SELECT *
FROM LOG;

SELECT *
FROM estado_solicitud_pedido;


SELECT *
FROM PRODUCTO;

SELECT *
FROM SOLICITUD_PEDIDO;

SELECT *
FROM PRODUCTO_CLIENTE;

SELECT *
FROM DETALLE_SOLICITUD_PEDIDO;

SELECT sp.id id_solicitud, sp.usuario_id, sp.fecha, dsp.id id_detalle, p.nombre_producto, pc.calidad, pc.cantidad
FROM SOLICITUD_PEDIDO sp,
     DETALLE_SOLICITUD_PEDIDO dsp,
     PRODUCTO_CLIENTE pc,
     PRODUCTO p
WHERE dsp.solicitud_pedido_id = sp.id
  AND dsp.producto_cliente_id = pc.id
  AND pc.producto_id = p.id
  AND sp.id = 104
ORDER BY sp.fecha desc;


SELECT *
FROM PRODUCTO_CLIENTE
WHERE ID IN (162, 187)
ORDER BY PRODUCTO_ID, CALIDAD



SELECT *
FROM DETALLE_SOLICITUD_PEDIDO
ORDER BY PRODUCTO_CLIENTE_ID;



SELECT *
FROM PRODUCTO_PRODUCTOR

SELECT *
FROM DETALLE_PEDIDO;
-- COMO SE ASOCIA A UN PEDIDO SI AUN NO SE GENERAA, YA QUE EL PRODUCTOR DECIDE ANTES DE CUANTO COBRAR?


SELECT *
FROM PRODUCTO_PRODUCTOR;



SELECT *
FROM PEDIDO;


-- APIs
-- DEVOLVER PRODUCTO_PRODUCTO SI EXISTE
-- 

SELECT *
FROM PRODUCTO_PRODUCTOR pp,
     PRODUCTO_CLIENTE PC
WHERE pp.PRODUCTO_ID = pc.PRODUCTO_ID

SELECT *
FROM SOLICITUD_PEDIDO sp,
     DETALLE_SOLICITUD_PEDIDO dsp,
     PRODUCTO_CLIENTE pc
WHERE dsp.SOLICITUD_PEDIDO_ID = sp.ID
  AND dsp.PRODUCTO_CLIENTE_ID = pc.ID;

SELECT pc.ID
FROM SOLICITUD_PEDIDO sp,
     DETALLE_SOLICITUD_PEDIDO dsp,
     PRODUCTO_CLIENTE pc
WHERE dsp.SOLICITUD_PEDIDO_ID = sp.id
  AND dsp.PRODUCTO_CLIENTE_ID = pc.ID

SELECT DSP.PRODUCTO_CLIENTE_ID,
       DSP.SOLICITUD_PEDIDO_ID,
       PC.PRODUCTO_ID,
       PC.CALIDAD,
       PC.CANTIDAD,
       P.NOMBRE_PRODUCTO,
       P.DESCRIPCION,
       P.IMAGEN
FROM DETALLE_SOLICITUD_PEDIDO DSP
         JOIN PRODUCTO_CLIENTE PC ON DSP.PRODUCTO_CLIENTE_ID = PC.ID
         JOIN PRODUCTO P ON PC.PRODUCTO_ID = P.ID
         JOIN SOLICITUD_PEDIDO SP ON DSP.SOLICITUD_PEDIDO_ID = SP.ID
WHERE dsp.solicitud_pedido_id = 184;


SELECT *
FROM SOLICITUD_PEDIDO;

SELECT *
FROM SOLICITUD_PEDIDO;

SELECT *
FROM PRODUCTO_CLIENTE;

SELECT *
FROM PRODUCTO_PRODUCTOR;

SELECT pp.id
FROM PRODUCTO_CLIENTE pc,
     PRODUCTO_PRODUCTOR pp
WHERE pc.PRODUCTO_ID = pp.PRODUCTO_ID


-- SOLICITUD_PEDIDO
-- DETALLE 1 -> PRODUCTO
-- DETALLE 2 -> PRODUCTO

-- SOLICITUD_PEDIDO.ID -> DETALLES -> PRODUCTO_CLIENTE

-- for DETALLE in DETALLES

-- END IF

-- RETURN puede_crear_pedido


SELECT *
FROM PRODUCTO_CLIENTE pc,
     PRODUCTO p,
     PRODUCTO_PRODUCTOR pp
WHERE pc.PRODUCTO_ID = p.ID
  AND pp.PRODUCTO_ID = p.id
  AND pc.CANTIDAD = pp.CANTIDAD
  AND pc.CALIDAD = pp.CALIDAD
  AND pc.id = 1

-- SELECT 
-- CASE CANTIDAD
--     WHEN < 1000 THEN
--     WHEN CANTIDAD > 1000 THEN
-- END
-- FROM PRODUCTO_PRODUCTOR
-- SELECT
--   product_name,
--   list_price,
--   CASE
--     WHEN list_price > 0 AND list_price  < 600
--         THEN 'Mass'
--     WHEN list_price >= 600 AND list_price < 1000
--         THEN 'Economy'
--     WHEN list_price >= 1000 AND list_price < 2000
--         THEN 'Luxury'
--     ELSE 
--         'Grand Luxury'
--   END product_group
-- FROM
--   products


-- DE PEDIDO TRAEREMOS EL ID DE LA SOLICITUD Y EL TOTAL
SELECT sp.id,
       SYSDATE AS "FECHA PEDIDO",
       1          "ESTADO POR DEFECTO",
       p.TOTAL,
       dp.PRODUCTO_PRODUCTOR_ID,
       dp.CANTIDAD,
       dp.PRECIO
FROM PEDIDO p,
     DETALLE_PEDIDO dp,
     SOLICITUD_PEDIDO sp
WHERE dp.PEDIDO_ID = p.ID
  AND p.SOLICITUD_PEDIDO_ID = sp.ID

INSERT INTO DETALLE_PEDIDO (PRODUCTO_PRODUCTOR_ID, PEDIDO_ID, PRECIO, CANTIDAD, PORCENTAJE_GANANCIA, TOTAL, GANANCIA,
                            TOTAL_SIN_GANANCIA)
VALUES (1,
        1,
        1000,
        10 --DEBE SER LA CANTIDAD QUE SOLICITO EL CLIENTE PARA ESE PRODUCTO
       )



SELECT *
FROM SOLICITUD_PEDIDO



INSERT INTO DETALLE_PEDIDO (PRODUCTO_PRODUCTOR_ID, PEDIDO_ID, PRECIO, CANTIDAD, TOTAL)
VALUES (1, 1, 1000, 10, TOTAL_SIN_GANANCIA + GANANCIA)

INSERT INTO DETALLE_PEDIDO (PRODUCTO_PRODUCTOR_ID, PEDIDO_ID, PRECIO, CANTIDAD, TOTAL)
VALUES (123, 2, 10000, 10, TOTAL_SIN_GANANCIA + GANANCIA)

SELECT *
FROM DETALLE_PEDIDO;

SELECT *
FROM ESTADO_SOLICITUD_PEDIDO

COMMIT;

SELECT *
FROM PRODUCTO_PRODUCTOR;


INSERT INTO DETALLE_PEDIDO (PRODUCTO_PRODUCTOR_ID, PEDIDO_ID, PRECIO, CANTIDAD, TOTAL)
VALUES (163, 21, 10000, 5, 50000)


SELECT *
FROM SOLICITUD_PEDIDO;

SELECT *
FROM PRODUCTO_PRODUCTOR

SELECT *
FROM PRODUCTO;

SELECT *
FROM PEDIDO;
COMMIT;



SELECT *
FROM PRODUCTO_PRODUCTOR_VENDIDO


SELECT *
FROM SOLICITUD_PEDIDO;



SELECT *
FROM PEDIDO;

SELECT *
FROM DETALLE_PEDIDO;

SELECT *
FROM PRODUCTO_PRODUCTOR;

SELECT *
FROM PRODUCTO_PRODUCTOR_VENDIDO;


SELECT pp.id,
       p.NOMBRE_PRODUCTO,
       pp.CALIDAD,
       pp.CANTIDAD,
       pp.PRODUCTOR_RUT,
       pp.PRECIO,
       ((pp.PRECIO * pp.CANTIDAD) * 0.05)                               AS "GANANCIA",
       (((pp.PRECIO * pp.CANTIDAD) * 0.05) + (pp.PRECIO * pp.CANTIDAD)) AS "TOTAL"
FROM PRODUCTO_PRODUCTOR pp
         JOIN PRODUCTO p ON pp.PRODUCTO_ID = p.ID
WHERE pp.ID IN (202, 201)

SELECT
           pp.id AS "PRODUCTO_PRODUCTOR_ID",
           pp.PRODUCTOR_RUT,
           p.NOMBRE_PRODUCTO,
           pp.CALIDAD,
           pc.CANTIDAD AS "CANTIDAD_PRODUCTO_CLIENTE",
           pp.PRECIO,
           ((pp.PRECIO * pc.CANTIDAD) * 0.05)                               AS "GANANCIA",
           (((pp.PRECIO * pc.CANTIDAD) * 0.05) + (pp.PRECIO * pc.CANTIDAD)) AS "TOTAL"
    FROM PRODUCTO_PRODUCTOR pp
             JOIN PRODUCTO p ON pp.PRODUCTO_ID = p.ID
             JOIN PRODUCTO_CLIENTE pc ON p.ID = pc.producto_id
    WHERE pp.ID = in_pp_id
    AND pc.ID = in_pc_id;


SELECT dsp.SOLICITUD_PEDIDO_ID, pc.id, pp.id, pp.PRODUCTOR_RUT, pp.CANTIDAD, pc.CANTIDAD
FROM DETALLE_SOLICITUD_PEDIDO dsp, 
     PRODUCTO_CLIENTE pc, 
     PRODUCTO_PRODUCTOR PP 
WHERE dsp.PRODUCTO_CLIENTE_ID = pc.ID
AND pp.PRODUCTO_ID = pc.PRODUCTO_ID;


SELECT sp.id, dsp.PRODUCTO_CLIENTE_ID, pp.id
FROM SOLICITUD_PEDIDO sp, DETALLE_SOLICITUD_PEDIDO dsp, PRODUCTO_PRODUCTOR pp
WHERE dsp.SOLICITUD_PEDIDO_ID = sp.ID
AND dsp.PRODUCTO_CLIENTE_ID = 188
AND pp.ID = 201

SELECT dsp.SOLICITUD_PEDIDO_ID, pp.id
FROM PRODUCTO_PRODUCTOR PP, 
     PRODUCTO_CLIENTE PC, 
     DETALLE_SOLICITUD_PEDIDO dsp
WHERE pp.PRODUCTO_ID = pc.PRODUCTO_ID   
AND pp.CALIDAD = pc.CALIDAD


SELECT pp.id pp.CALIDAD, pp.CANTIDAD
FROM PRODUCTO p, PRODUCTO_PRODUCTOR pp
WHERE pp.PRODUCTO_ID = p.ID
AND pp.PRODUCTO_ID = 22
ORDER BY p.id DESC

COMMIT;

SELECT pc.ID, pc.CANTIDAD, pc.CALIDAD
FROM DETALLE_SOLICITUD_PEDIDO dsp, PRODUCTO_CLIENTE pc
WHERE dsp.PRODUCTO_CLIENTE_ID = pc.ID
ORDER BY dsp.ID DESC


SELECT *
FROM PEDIDO


SELECT *
FROM LOG;

EXEC SP_INSERT_PEDIDO_Y_DETALLE('{{\"pedido\":{\"solicitud_id\":172,\"detalle_pedido\":[{\"producto_id\":4,\"productor_id\":\"1-1\",\"calidad\":5,\"cantidad\":111,\"precio\":5000}]}}}');

COMMIT;


SELECT *
FROM PEDIDO;


SELECT os.ID AS "OFERTA_SUBASTA_ID",
       os.SUBASTA_ID, 
       os.VALOR AS "MONTO_OFERTADO",
       s.PRECIO_PISO,
       os.FECHA AS "FECHA_OFERTA",
       s.FECHA AS "FECHA_INICIO_SUBASTA", u.RUT
FROM OFERTA_SUBASTA os JOIN USUARIO u ON os.USUARIO_ID = u.RUT
                        JOIN SUBASTA s ON os.SUBASTA_ID = s.ID
ORDER BY os.SUBASTA_ID


SELECT *
FROM SUBASTA;

EXEC SP_LOGIN('17385929-5', '663401993');
COMMIT;
SELECT u.rut, u.clave, r.NOMBRE_ROL
FROM USUARIO u, ROL r
WHERE u.ROL_ID = r.ID

UPDATE USUARIO SET CLAVE = 'NjYzNDAxOTkz' WHERE rut = '17385929-5'


SELECT *
FROM DETALLE_PEDIDO;

-- PERMITE SABER LA VERSION DEL MOTOR DE ORACLE
SELECT * FROM v$version;

SELECT *
FROM LOG;

SELECT *
FROM PEDIDO;

SELECT *
FROM OFERTA_SUBASTA os 

SELECT *
FROM PEDIDO WHERE SOLICITUD_PEDIDO_ID = 172

SELECT *
FROM SOLICITUD_PEDIDO
ORDER BY ID DESC;

SELECT s.*, os.*
FROM OFERTA_SUBASTA os JOIN SUBASTA s ON os.SUBASTA_ID = s.ID 
WHERE s.PEDIDO_ID  = 125
ORDER BY os.FECHA DESC

SELECT *
FROM PEDIDO WHERE ID = 125;

SELECT *
FROM USUARIO;


SELECT s.ID
    FROM SUBASTA s
         JOIN PEDIDO P on s.PEDIDO_ID = P.ID
         WHERE P.ID = 126
         
         
SELECT u.RUT, c.*
FROM USUARIO u JOIN CONTRATO C ON u.CONTRATO_ID = c.ID


-- PARA SUMAR MESES A LA FECHA ACTUAL!
SELECT ADD_MONTHS(sysdate, 24) 
FROM DUAL

SELECT *
FROM CONTRATO;

CREATE OR REPLACE PROCEDURE DEV.SP_INSERT_CONTRATO (
IN_RUT              IN CONTRATO.USUARIO_ID%TYPE,
OUT_GLOSA           OUT VARCHAR2,
OUT_ESTADO          OUT NUMBER,
OUT_MENSAJE_SALIDA  OUT VARCHAR2
) AS 
BEGIN

    INSERT INTO DEV.CONTRATO (FECHA_INICIO, FECHA_FIN, USUARIO_ID)
    VALUES (SYSDATE, ADD_MONTHS(sysdate, 24)) , IN_RUT)
    RETURNING 'CONTRATO CREADO CORRECTAMENTE' INTO OUT_MENSAJE_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA  := DEV.FN_GET_GLOSA_ERROR;

END;